### ISSUE TITLE
Rewrite build process to follow realistic setup

### ISSUE THREAD

**Issue by mcloughlan** [RMIT-Competition-Rocketry/GCS#150]
re-write the build setup to use `bash setup.sh` and `FetchContent` instead of building everything from scratch. Make sure to cache the `_deps` so they aren't re-downloaded each time.

**Comment by mcloughlan** [comment]
Also setup lib cache in a way that doesn't hard code keys. Add the version in there somewhere

use this

```yml
env:
  PB_VERSION: 30.1
  ...

# in cache step:
key: protobuf-${{ runner.os }}-v${{ env.PB_VERSION }}
```
